server:
  host: "localhost"
  port: 8080

database:
  name: "mgm_db"
  cluster: "licensecluster.skrknve.mongodb.net"
  username: "marin_mongo" 
  password: "NapocaMongo10"
  options: "retryWrites=true&w=majority"

security:
  authtokenduration: 15 # in minutes
  refreshtokenduration: 120 # in minutes
  tokensecret: "mysecret"

logging:
  filename: "log.txt"
  maxsize: 512
  maxbackups: 3
  maxage: 1
  compress: false
  debug: false

redis: 
  protocol: "tcp"
  url: "localhost:6379"
  maxidle: 10
  maxactive: 100
  count: 100
  waittime: 200 # ms

notificiations: 
  protocol: "ws" # ws or sse
  ws:
    timeout: #all in ms
      handshake: 1000
      write: 200
      token: 1000
  sse:
    flush: true
    ping:
      enabled: true
      interval: 15 # in s
    